<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251228060752 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, amount INT NOT NULL, description VARCHAR(255) DEFAULT NULL, icon VARCHAR(50) DEFAULT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, wallet_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D3A8DA6539B0606 ON expense (uid)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6712520F3 ON expense (wallet_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6B03A8386 ON expense (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6896DBBDE ON expense (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6C76F1F52 ON expense (deleted_by_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, gender VARCHAR(10) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('CREATE TABLE wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, total_amount INT DEFAULT 0 NOT NULL, label VARCHAR(255) NOT NULL, payments_due JSON DEFAULT \'[]\' NOT NULL, last_settlement_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7C68921F539B0606 ON wallet (uid)');
        $this->addSql('CREATE INDEX IDX_7C68921FB03A8386 ON wallet (created_by_id)');
        $this->addSql('CREATE INDEX IDX_7C68921F896DBBDE ON wallet (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_7C68921FC76F1F52 ON wallet (deleted_by_id)');
        $this->addSql('CREATE TABLE xuser_wallet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) DEFAULT \'user\' NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, wallet_id INT NOT NULL, target_user_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B2E09AB712520F3 ON xuser_wallet (wallet_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09AB6C066AFE ON xuser_wallet (target_user_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09ABB03A8386 ON xuser_wallet (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09AB896DBBDE ON xuser_wallet (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_2B2E09ABC76F1F52 ON xuser_wallet (deleted_by_id)');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921FB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921F896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wallet ADD CONSTRAINT FK_7C68921FC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09AB712520F3 FOREIGN KEY (wallet_id) REFERENCES wallet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09AB6C066AFE FOREIGN KEY (target_user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09ABB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09AB896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE xuser_wallet ADD CONSTRAINT FK_2B2E09ABC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6712520F3');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6B03A8386');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6896DBBDE');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6C76F1F52');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921FB03A8386');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921F896DBBDE');
        $this->addSql('ALTER TABLE wallet DROP CONSTRAINT FK_7C68921FC76F1F52');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09AB712520F3');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09AB6C066AFE');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09ABB03A8386');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09AB896DBBDE');
        $this->addSql('ALTER TABLE xuser_wallet DROP CONSTRAINT FK_2B2E09ABC76F1F52');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE wallet');
        $this->addSql('DROP TABLE xuser_wallet');
    }
}
